### PR TITLE
Fix/vim tabline

### PR DESCRIPTION
**Pull request by hovsater**
Right now, the tab line isn't visible. This pull request addresses this by making it mimic the colors of the status line.

The tab line is using the colors of an inactive status line and the currently selected tab is using the colors of an active status line. I'm not sure if that sticks out too much? Perhaps an alternative would be to always use the active status line colors and only distinguish the tabs from the active one using **bold**.

### CODE REVIEW

**Comment by asmvik** [comment]
Do you have a screenshot maybe? I don't use tabs in vim personally, so this does not affect me, but I'm definitely open to ironing out inconsistencies and/or incomplete styling.

**Comment by hovsater** [comment]
@koekeishiya sure thing!

tabline

**Comment by asmvik** [comment]
Right so I haven't actually looked at how the default statusline was styled either.
Here is a screencast of how I've set up the different modes using the vim-airline theme I referenced earlier:
Screen Recording 2020-03-18 at 12 04 53

I have adjusted the colorscheme to look the way I would want if vim-airline was not running:
Screenshot 2020-03-18 at 12 20 53

You could make the tabline follow that scheme if you'd like.

**Comment by hovsater** [comment]
Thanks once again. Those colors were much more pleasant to work with. 🙂 

Here is the updated screenshot:

updated-tabline

**Pull request merged**
